// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © smbolster

//@version=4

study("Simple Moving Averages","SMAs", overlay=true)

    


int secondsInDay = 390
int periodsInBar = 0




sma1 = input(title="SMA Level 1", type=input.integer,defval=10)
sma2 = input(title="SMA Level 2", type=input.integer,defval=20)
sma3 = input(title="SMA Level 3", type=input.integer,defval=100)
sma4 = input(title="SMA Level 4", type=input.integer,defval=200)



smaLine1 = sma(close,sma1)
smaLine2 = sma(close,sma2)
smaLine3 = sma(close,sma3)
smaLine4 = sma(close,sma4)



plot(smaLine1, color=color.green, title="SMA Level 1")
plot(smaLine2, color=color.purple, title="SMA Level 2")
plot(smaLine3, color=#FF0000, title="SMA Level 3" )
plot(smaLine4, color=#FF0000, title="SMA Level 4" )
